name: fat_framework
description: A Fat Framework for Flutter.
version: 0.0.69
author:
homepage: https://gtihub.com/zhangdi/fat-framework

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 事件驱动
  event_bus: ^1.1.0
  # 状态管理
  provider: ^4.0.0
  # 设备信息
  device_info: ^0.4.0
  # 通知
  flutter_local_notifications: ^1.4.0
  # 偏好设置
  shared_preferences: ^0.5.7
  # 图片选择器
  image_picker: ^0.6.6
  # 图片缓存
  cached_network_image: ^2.1.0
  # 图标
  flutter_icons: ^1.1.0
  # Toast 消息
  toast: ^0.1.5
  # Http 请求
  dio: ^3.0.9
  # 应用包信息
  package_info: ^0.4.0
  # 音频播放器
  audioplayers: ^0.15.1
  # 震动
  vibration: ^1.4.0
  # 权限管理
  permission_handler: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
